const { createCommerce } = require('./createCommerce');
const { MySQLUserRepository } = require('../infrastructure/repositories/MySQLUserRepository');
const { MySQLProductRepository } = require('../infrastructure/repositories/MySQLProductRepository');
const { MySQLProductRequestRepository } = require('../infrastructure/repositories/MySQLProductRequestRepository');
const { MySQLOrderRepository } = require('../infrastructure/repositories/MySQLOrderRepository');
const { createRegisterUser } = require('../application/use-cases/registerUser');
const { createLoginUser } = require('../application/use-cases/loginUser');
const { createListPendingUsers } = require('../application/use-cases/listPendingUsers');
const { createUpdateUserStatus } = require('../application/use-cases/updateUserStatus');
const { createListProducts } = require('../application/use-cases/listProducts');
const { createCreateProduct } = require('../application/use-cases/createProduct');
const { createUpdateProduct } = require('../application/use-cases/updateProduct');
const { createDeleteProduct } = require('../application/use-cases/deleteProduct');
const { createCreateProductRequest } = require('../application/use-cases/createProductRequest');
const { createListPendingProductRequests } = require('../application/use-cases/listPendingProductRequests');
const { createUpdateProductRequestStatus } = require('../application/use-cases/updateProductRequestStatus');
const { createCreateOrder } = require('../application/use-cases/createOrder');
const { createListMyOrders } = require('../application/use-cases/listMyOrders');
const { createListPendingOrders } = require('../application/use-cases/listPendingOrders');
const { createUpdateOrderStatus } = require('../application/use-cases/updateOrderStatus');

const {BcryptPasswordHasher}=require('../infrastructure/services/BcryptPasswordHasher');
const {JwtTokenService}=require('../infrastructure/services/JwtTokenService');
const {NodeCryptoService}=require('../infrastructure/services/NodeCryptoService');
const {MySQLUnitOfWork}=require('../infrastructure/database/MySQLUnitOfWork');
const {createResolveProviderOrder}=require('../application/use-cases/resolveProviderOrder');
const {createResolveProductRequest}=require('../application/use-cases/resolveProductRequest');
const {createAuthenticateSession}=require('../application/use-cases/authenticateSession');
const {createSubmitProductChange}=require('../application/use-cases/submitProductChange');
const createServices=(pool,env=process.env)=>{
 const passwordHasher=new BcryptPasswordHasher(),crypto=new NodeCryptoService(),tokenService=new JwtTokenService(env.JWT_SECRET),unitOfWork=new MySQLUnitOfWork(pool);
 const resolveProviderOrder=createResolveProviderOrder({unitOfWork}),resolveProductRequest=createResolveProductRequest({unitOfWork});
  const userRepository = new MySQLUserRepository(pool);
  const productRepository = new MySQLProductRepository(pool);
  const productRequestRepository = new MySQLProductRequestRepository(pool);
  const orderRepository = new MySQLOrderRepository(pool);
  const registerUser = createRegisterUser({ userRepository,passwordHasher,crypto });
  const loginUser = createLoginUser({ userRepository,passwordHasher,tokenService });
  const listPendingUsers = createListPendingUsers({ userRepository });
  const updateUserStatus = createUpdateUserStatus({ userRepository });
  const listProducts = createListProducts({ productRepository });
  const createProduct = createCreateProduct({ productRepository });
  const updateProduct = createUpdateProduct({ productRepository });
  const deleteProduct = createDeleteProduct({ productRepository });
  const createProductRequest = createCreateProductRequest({ productRepository, productRequestRepository });
  const listPendingProductRequests = createListPendingProductRequests({ productRequestRepository });
  const updateProductRequestStatus = createUpdateProductRequestStatus({ resolveProductRequest });
  const createOrder = createCreateOrder({ orderRepository });
  const listMyOrders = createListMyOrders({ orderRepository });
  const listPendingOrders = createListPendingOrders({ orderRepository });
  const updateOrderStatus = createUpdateOrderStatus({ resolveProviderOrder });
return {authenticateSession:createAuthenticateSession({userRepository}),commerce:createCommerce(pool,env),registerUser,loginUser,listPendingUsers,updateUserStatus,listProducts,createProduct,updateProduct,deleteProduct,createProductRequest,listPendingProductRequests,updateProductRequestStatus,createOrder,listMyOrders,listPendingOrders,updateOrderStatus,submitProductChange:createSubmitProductChange({createProduct,deleteProduct,createProductRequest})};
};
module.exports={createServices};
