CREATE TABLE IF NOT EXISTS user_security (
  user_id BIGINT PRIMARY KEY,
  version INT CHECK (version >= 0) NOT NULL DEFAULT 0,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS customer_addresses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  address JSONB NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS shop_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  request_key VARCHAR(64) NOT NULL,
  request_hash CHAR(64) NOT NULL,
  currency CHAR(3) NOT NULL DEFAULT 'MXN',
  subtotal_cents BIGINT CHECK (subtotal_cents >= 0) NOT NULL,
  shipping_cents BIGINT CHECK (shipping_cents >= 0) NOT NULL,
  total_cents BIGINT CHECK (total_cents >= 0) NOT NULL,
  address JSONB NOT NULL,
  payment_method TEXT CHECK (payment_method IN ('contra_entrega','transferencia')) NOT NULL,
  payment_status TEXT CHECK (payment_status IN ('pendiente','pagado','reembolsado')) NOT NULL DEFAULT 'pendiente',
  status TEXT CHECK (status IN ('recibido','confirmado','preparando','enviado','entregado','cancelado')) NOT NULL DEFAULT 'recibido',
  carrier VARCHAR(120) NULL,
  tracking_number VARCHAR(160) NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,


  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS shop_order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL,
  product_id BIGINT NULL,
  product_name VARCHAR(160) NOT NULL,
  image_url TEXT NULL,
  quantity INT CHECK (quantity > 0) NOT NULL,
  unit_price_cents BIGINT CHECK (unit_price_cents >= 0) NOT NULL,
  FOREIGN KEY (order_id) REFERENCES shop_orders(id) ON DELETE CASCADE,
  FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS shop_notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  order_id BIGINT NULL,
  message VARCHAR(500) NOT NULL,
  is_read BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (order_id) REFERENCES shop_orders(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS password_reset_tokens (
  token_hash CHAR(64) PRIMARY KEY,
  user_id BIGINT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS shop_fulfillment (
  order_id BIGINT PRIMARY KEY,
  instructions TEXT NOT NULL,
  updated_by BIGINT NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (order_id) REFERENCES shop_orders(id) ON DELETE CASCADE,
  FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX IF NOT EXISTS shop_idempotency ON shop_orders (user_id, request_key);
CREATE INDEX IF NOT EXISTS shop_history ON shop_orders (user_id, created_at);

DROP TRIGGER IF EXISTS shop_orders_touch_updated_at ON shop_orders;
CREATE TRIGGER shop_orders_touch_updated_at BEFORE UPDATE ON shop_orders FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
DROP TRIGGER IF EXISTS shop_fulfillment_touch_updated_at ON shop_fulfillment;
CREATE TRIGGER shop_fulfillment_touch_updated_at BEFORE UPDATE ON shop_fulfillment FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
