CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(254) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role TEXT CHECK (role IN ('gestor', 'proveedor', 'super_admin', 'cliente')) NOT NULL,
  status TEXT CHECK (status IN ('pendiente', 'aprobado', 'rechazado')) NOT NULL DEFAULT 'pendiente',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);



CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  nombre VARCHAR(160) NOT NULL,
  descripcion TEXT NOT NULL,
  precio DECIMAL(12, 2) CHECK (precio >= 0) NOT NULL,
  categoria VARCHAR(100) NOT NULL,
  imagen_url TEXT NULL,
  stock INT CHECK (stock >= 0) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS product_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  requester_id BIGINT NOT NULL,
  reviewer_id BIGINT NULL,
  request_type TEXT CHECK (request_type IN ('crear', 'eliminar')) NOT NULL,
  product_id BIGINT NULL,
  product_data JSONB NOT NULL,
  status TEXT CHECK (status IN ('pendiente', 'aprobado', 'rechazado')) NOT NULL DEFAULT 'pendiente',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  reviewed_at TIMESTAMPTZ NULL DEFAULT NULL,
  PRIMARY KEY (id),


  CONSTRAINT product_requests_requester_fk FOREIGN KEY (requester_id) REFERENCES users (id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT product_requests_reviewer_fk FOREIGN KEY (reviewer_id) REFERENCES users (id)
    ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  product_id BIGINT NOT NULL,
  quantity INT NOT NULL,
  status TEXT CHECK (status IN ('pendiente', 'aprobado', 'rechazado')) NOT NULL DEFAULT 'pendiente',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),


  CONSTRAINT orders_user_fk FOREIGN KEY (user_id) REFERENCES users (id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT orders_product_fk FOREIGN KEY (product_id) REFERENCES products (id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT orders_quantity_positive CHECK (quantity > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS users_email_unique ON users (email);
CREATE INDEX IF NOT EXISTS products_category_index ON products (categoria);
CREATE INDEX IF NOT EXISTS products_name_index ON products (nombre);
CREATE INDEX IF NOT EXISTS product_requests_status_created_index ON product_requests (status, created_at, id);
CREATE INDEX IF NOT EXISTS product_requests_product_index ON product_requests (product_id);
CREATE INDEX IF NOT EXISTS orders_user_created_index ON orders (user_id, created_at);
CREATE INDEX IF NOT EXISTS orders_status_created_index ON orders (status, created_at);

CREATE OR REPLACE FUNCTION touch_updated_at() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = CURRENT_TIMESTAMP; RETURN NEW; END;
$$;
DROP TRIGGER IF EXISTS products_touch_updated_at ON products;
CREATE TRIGGER products_touch_updated_at BEFORE UPDATE ON products FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
