const ERROR_CODES = Object.freeze({VALIDATION:'VALIDATION',UNAUTHORIZED:'UNAUTHORIZED',FORBIDDEN:'FORBIDDEN',NOT_FOUND:'NOT_FOUND',CONFLICT:'CONFLICT',UNAVAILABLE:'UNAVAILABLE',DUPLICATE:'DUPLICATE',REFERENCED:'REFERENCED',MISSING_REFERENCE:'MISSING_REFERENCE'});
const fail = (message, code = ERROR_CODES.VALIDATION) => Object.assign(new Error(message), {code});
module.exports = {ERROR_CODES,fail};
